直積とINNER JOIN用のテーブルを作成・.gitignoreファイルの追加
kentaroamenomori/training pull request #3
Opened 2022-07-12 08:03 UTC by kentaroamenomori

2022-07-13 04:06 UTC, flect-ryogo108 requested changes
テーブルの作成自体はOKです。書き方についてコメントをさせて頂きました。ご確認ください。

2022-07-13 04:06 UTC, flect-ryogo108 commented on rdb/inner_join/00_create_table.sql
> +CREATE TABLE employees(id integer PRIMARY KEY, name text NOT NULL, date_joined date NOT NULL, phone_number text);
`text`, `integer`, `date`などの型も大文字にしてください。

2022-07-14 02:11 UTC, flect-ryogo108 approved these changes
OKだと思います。
(1箇所だけ簡単な修正箇所を指摘させて頂きましたので、それだけ、ご確認お願いします。)

2022-07-14 02:11 UTC, flect-ryogo108 commented on rdb/inner_join/00_create_table.sql
> +CREATE TABLE divisions(id text PRIMARY KEY, name text NOT NULL);
ここの`text`も大文字にしておいて下されば、と思います。

2022-07-14 02:39 UTC, kentaroamenomori commented on rdb/inner_join/00_create_table.sql
> +CREATE TABLE divisions(id text PRIMARY KEY, name text NOT NULL);
こちら修正しました。

2022-07-14 03:15 UTC, merged

2022-07-14 05:44 UTC, dyamashita-flect commented on rdb/inner_join/00_create_table.sql
> +);
明らかに固定長の文字列については可変長文字列ではなく固定長文字列として宣言した方が良いと思います。これは以下の２つの特性によります：

- 基本的に処理速度は固定長文字列の方が優位
    - ただしメモリ使用量的には不利になる可能性があるので注意
- 可変長文字列だと明らかに誤った長さのデータが来た際にそのまま格納されてしまう
    - 固定帳文字列だと長すぎるデータは切り捨てられる
    - 短すぎる文字列には不足文字数分だけ空白が付与されるので注意

どちらの特性も一長一短ですが、電話番号などは固定長にされることが多いですね。

2022-07-14 05:44 UTC, dyamashita-flect commented on rdb/inner_join/00_create_table.sql
> +	date_joined DATE NOT NULL,
特に誤りというわけではないのですが、日付型は ~ at の形で宣言されることが多いですね。作成日時なら `created_at` というような感じです。

型名と同じ情報を変数名に入れたくないことに由来する習慣だと思うので、個人的にはどちらの流儀でも良いとは思います。

2022-07-14 05:55 UTC, dyamashita-flect commented on rdb/inner_join/00_create_table.sql
> +);
あと余談ですが SQL ではカンマを先頭に持ってくる風習がありますね。

```sql
CREATE TABLE employees
    ( id           INTEGER PRIMARY KEY
    , name         TEXT    NOT NULL
    , date_joined  DATE    NOT NULL
    , phone_number TEXT
    );
```

これはカラム追加時の手間を減らすための工夫です。（縦揃えインデントはただの趣味）

2022-07-14 11:17 UTC, nobuyukiishii commented
従業員番号のカラム名はidでないほうがよいと思います。idは、一般的にidカラムで使うことがあるので、混同します。